# Generated by Django 5.2.7 on 2025-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
